CREATE TABLE IF NOT EXISTS CLIENTES (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    SALDO DECIMAL(10,2) NOT NULL DEFAULT 0,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);